#pragma once

#include "Animation/Enums.h"
#include "Animation/Keyframes.h"
#include "Animation/Motion.h"
#include "File/AnimationFile.h"
#include "File/FileHeaders.h"
#include "File/MetaBlockType.h"
#include "File/MetaData.h"
#include "File/ModelFile.h"
#include "File/NJBlockUtility.h"
#include "File/Structs/MetaWeight.h"
#include "File/Structs/MetaWeightNode.h"
#include "File/Structs/MetaWeightVertex.h"
#include "Mesh/Attach.h"
#include "Mesh/AttachDispatch.h"
#include "Mesh/Buffer/BufferMesh.h"
#include "Mesh/Chunk/ChunkAttach.h"
#include "Mesh/Chunk/ChunkTypeExtensions.h"
#include "Mesh/Chunk/PolyChunk.h"
#include "Mesh/Chunk/PolyChunkDispatch.h"
#include "Mesh/Chunk/PolyChunkType.h"
#include "Mesh/Chunk/PolyChunks/BitsChunk.h"
#include "Mesh/Chunk/PolyChunks/MaterialBumpChunk.h"
#include "Mesh/Chunk/PolyChunks/MaterialChunk.h"
#include "Mesh/Chunk/PolyChunks/StripChunk.h"
#include "Mesh/Chunk/PolyChunks/TextureChunk.h"
#include "Mesh/Chunk/Structs/ChunkCorner.h"
#include "Mesh/Chunk/Structs/ChunkStrip.h"
#include "Mesh/Chunk/Structs/ChunkVertex.h"
#include "Mesh/Chunk/VertexChunk.h"
#include "Mesh/Chunk/VertexChunkType.h"
#include "Mesh/Chunk/WeightStatus.h"
#include "Mesh/Converters/ActivePolyChunkHelper.h"
#include "Mesh/Converters/ChunkBufferConverter.h"
#include "Mesh/Enums.h"
#include "Mesh/Weighted/WeightedMesh.h"
#include "ObjectData/Enums/ModelFormat.h"
#include "ObjectData/Enums/NodeAttributes.h"
#include "ObjectData/Enums/RotationUpdateMode.h"
#include "ObjectData/Node.h"
#include "Structs/BaseLUT.h"
#include "Structs/BAMSFHelper.h"
#include "Structs/Bounds.h"
#include "Structs/Color.h"
#include "Structs/ColorIOType.h"
#include "Structs/DebugStringExtensions.h"
#include "Structs/Endian.h"
#include "Structs/EndianIOExtensions.h"
#include "Structs/EndianStackReader.h"
#include "Structs/EndianStackWriter.h"
#include "Structs/FloatIOType.h"
#include "Structs/LabeledArray.h"
#include "Structs/MathCompat.h"
#include "Structs/MathHelper.h"
#include "Structs/Matrix4x4.h"
#include "Structs/MatrixUtilities.h"
#include "Structs/PointerIO.h"
#include "Structs/PointerLUT.h"
#include "Structs/PositionNormal.h"
#include "Structs/Quaternion.h"
#include "Structs/QuaternionUtilities.h"
#include "Structs/Vector2.h"
#include "Structs/Vector3.h"
#include "Structs/Vector4.h"
#include "Structs/VectorUtilities.h"
#include "Testing/Slice8TestApi.h"
#include "Testing/Slice9TestApi.h"

namespace Sa3Dport {

inline constexpr const char* kProjectName = "Sa3Dport";

} // namespace Sa3Dport
